name: CI_LOAD_TESTING

on:
  push:
    workflow_dispatch:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: sudo npm install -g loadtest

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd tasks-crud && pip install -r requirements.txt

      - name: Start the server in the background with uvicorn
        run: |
          cd tasks-crud && uvicorn app.main:app -host 0.0.0.0 --port 8080 --reload & echo $! > uvicorn.pid && sleep 10 && cat uvicorn.pid

      - name: Run Load Testing
        run: |
          cd tasks-crud && loadtest -c 10 --rps 100 http://0.0.0.0:8080/api/v1/tasks
